Add `tweak()` method for `BIP32Interface`
bitcoinjs/bip32 pull request #66
Opened 2022-09-14 14:15 UTC by motorina0

This is a mirror of https://github.com/bitcoinjs/ecpair/pull/8

2022-09-19 09:22 UTC, junderw requested changes
LGTM other than the private key tweak will actually return a Bip32 object. We should do the same we do for public and make a simple wrapper.

2022-09-19 09:22 UTC, junderw commented on ts-src/bip32.ts
> +      return fromPrivateKey(
Even though the TS type doesn't have the derive methods etc... The actual returned type does.

We should probably create a thin wrapper that only provides the needed methods and attributes.

2022-09-19 16:16 UTC, motorina0 commented
Done. Extracted `Bip32Signer` parent class.

2022-09-25 11:48 UTC, junderw approved these changes

2022-09-25 11:49 UTC, merged